# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'smap' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.5'
  pod 'IQKeyboardManagerSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'SnackBar.swift'
  pod 'YPImagePicker'
  pod 'SwiftyStoreKit'
  pod 'Google-Mobile-Ads-SDK'
  pod 'GoogleMobileAdsMediationTestSuite'

  # Pods for smap

end
